"""Assemble and render the signed triage memo -- the deliverable artifact.

The memo's shape mirrors how a real maintainer security team writes a triage
response: a clear verdict up front, exactly what was tested and what happened,
a per-claim assessment, what is being deferred to a human, and a sign-off block
that is never auto-filled. The renderer produces Markdown a person could paste
into a HackerOne response and sign.
"""
from __future__ import annotations

from pathlib import Path

from slopgate.agent.schema import Claim, ReproEvidence, TriageMemo, Verdict

_VERDICT_LABEL = {
    Verdict.CONFIRMED: "CONFIRMED — reproduced",
    Verdict.NOT_REPRODUCIBLE: "NOT REPRODUCIBLE",
    Verdict.INSUFFICIENT: "INSUFFICIENT EVIDENCE — needs human review",
}


def render_markdown(memo: TriageMemo) -> str:
    lines = [
        f"# Vulnerability Triage Memo — {memo.report_id}",
        "",
        f"**Package:** {memo.package} {memo.affected_version}  ",
        f"**Verdict:** {_VERDICT_LABEL[memo.verdict]}",
        "",
        "## Assessment",
        memo.summary,
        "",
    ]

    if memo.reproduction:
        r = memo.reproduction
        lines += [
            "## Reproduction attempt",
            f"- **Environment:** `{r.env_id}`",
            f"- **Outcome:** `{r.outcome}`" + ("  ✅ reproduced" if r.reproduced else ""),
            f"- **Command:** `{r.command}`",
            "",
            "```",
            (r.stdout_tail or "(no output)").strip(),
            "```",
            "",
        ]

    if memo.claims:
        lines += ["## Claim-by-claim", ""]
        for c in memo.claims:
            mark = {True: "supported", False: "UNSUPPORTED", None: "unverified"}[c.supported]
            lines.append(f"- **[{mark}]** {c.text}")
            if c.evidence:
                lines.append(f"  - _evidence:_ {c.evidence}")
        lines.append("")

    if memo.challenger_note:
        lines += ["## Adversarial review", memo.challenger_note, ""]

    if memo.abstentions:
        lines += ["## Deferred to human reviewer", ""]
        lines += [f"- {a}" for a in memo.abstentions]
        lines.append("")

    lines += [
        "## Sign-off",
        f"- **Reviewed by:** {memo.reviewer}",
        "- _No consequential action (CVE assignment, public disclosure, reporter "
        "reward) may be taken until a qualified human reviewer signs above._",
        "",
        "---",
        f"_Generated by SlopGate · {memo.llm_calls} LLM calls · "
        f"{memo.total_tokens} tokens · ~${memo.est_cost_usd:.4f} · "
        f"{memo.wall_latency_s:.1f}s._",
    ]
    return "\n".join(lines)


def save_memo(memo: TriageMemo, out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    md = out_dir / "memo.md"
    md.write_text(render_markdown(memo), encoding="utf-8")
    js = out_dir / "memo.json"
    memo.save_json(js)
    return md, js
